// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ff2nC
IntegerMatrix ff2nC(int p);
RcppExport SEXP _StatComp21081_ff2nC(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(ff2nC(p));
    return rcpp_result_gen;
END_RCPP
}
// gibbsC
NumericMatrix gibbsC(int a, int b, int n, int N, int thin);
RcppExport SEXP _StatComp21081_gibbsC(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP NSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsC(a, b, n, N, thin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp21081_ff2nC", (DL_FUNC) &_StatComp21081_ff2nC, 1},
    {"_StatComp21081_gibbsC", (DL_FUNC) &_StatComp21081_gibbsC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp21081(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
