# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A function generates an index matrix
#' @description A function generates an index matrix
#' @param p the dimension of the matrix, \code{p} shouldn't be large
#' @return a \code{2^s*s} index matrix filled with 0 and 1
#' @examples 
#' \dontrun{
#' Index <- ff2n(3)
#' print(Index)
#' }
#' @export
ff2nC <- function(p) {
    .Call('_StatComp21081_ff2nC', PACKAGE = 'StatComp21081', p)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a the parameter of distribution
#' @param b the parameter of distribution
#' @param n the parameter of distribution
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(2,2,10,100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
NULL

gibbsC <- function(a, b, n, N, thin) {
    .Call('_StatComp21081_gibbsC', PACKAGE = 'StatComp21081', a, b, n, N, thin)
}

